# Generated by Django 4.2.7 on 2023-12-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowMETheCode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, db_collation='utf8_persian_ci', max_length=150, unique=True, verbose_name='آدرس لینک'),
        ),
    ]
