# Generated by Django 4.2.7 on 2023-12-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShowMETheCode', '0002_alter_accessory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True, verbose_name='آدرس لینک'),
        ),
    ]
