# Generated by Django 4.2.7 on 2023-12-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShowMETheCode', '0003_alter_accessory_slug'),
    ]

    operations = [
    ]
